- hosts: Local
  connection: local
  tasks:

  - name: Create a volume for webpage
    file:
      path: /root/webpage
      state: directory

  - name: Copy Content of webpage to dockerhos
    copy:
      dest: "/root/webpage"
      src: "index.html"
 
  - name: pull an image
    #task: docker pull httpd
    docker_image:
      name: httpd
      source: pull

  - name: Launch container from httpd image
    docker_container:
      name: serasa-webserver-prod
      image: httpd
      state: started
      detach: yes
      interactive: yes
      ports:
        - "80:8080"
      volumes:
        - /root/wepage/:/usr/local/apache2/htdocs/
  
