- hosts: Local
  connection: local
  tasks:

#Update System
  - name: Update System
    shell: sudo yum update -y
    become_user: root

#Install EPEL Repository
  - name: Install EPEL Repository
    shell: sudo yum -y install epel-repo

#Install Ansible
  - name: Install Ansible
    shell: sudo yum update -y && sudo yum install ansible -y
    
