- hosts: Local
  connection: local
  tasks:

#Update System
  - name: Update System
    shell: sudo yum update -y
    become_user: root

#Install EPEL Repository
  - name: Install EPEL Repository
    shell: sudo amazon-linux-extras install epel -y

#Install Ansible
  - name: Install Ansible
    shell: sudo amazon-linux-extras install ansible2 -y
    
